# Generated by Django 5.1.4 on 2025-03-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.CharField(max_length=3)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('data', models.DateField()),
            ],
            options={
                'unique_together': {('moeda', 'data')},
            },
        ),
    ]
